title: Coder Yoda
author: GitHub User
email: abdumalik2014@gmail.com
theme: jekyll-theme-cayman
description: 
|
  For now, I plan to write some of my new findings, explorations related to programming. 
  Maybe something beyond programming will also start appearing here.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  abdu95 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
