title: Coder Yoda
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  For now, I plan to write some of my new findings, explorations related to programming. 
  Maybe something beyond programming will also start appearing here.
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  abdu95 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
